function generateReport(conn, idUser, idQImage)
    conn = database('conn_scih', 'uqrpef8uvj0gk5k7', 'hS0C86ybuxlTFNVYSSto');
    idUser = 2;
    idQImage = 32;
    date = datetime;

    % Datos del usuario
    query = strcat("SELECT * FROM User WHERE idUser = ", string(idUser));

    try
        user = fetch(conn, query);
    catch e
        msgbox(strcat("Error ", char(e.message)), "Warning", "error");
    end

    % Obtain number of case
    nameSpl = split(string(user.name), " ");
    nameIn = "";
    for i=1 : length(nameSpl)
        wordSpl = split(string(nameSpl(i)), "");
        nameIn = strcat(nameIn, upper(wordSpl(2)));
    end
    

    nCase = strcat(nameIn, "_", string(user.nReports + 1),"_",string(date.Day), string(date.Month), string(date.Year));

    % Datos de la imagen
    query = strcat("SELECT * FROM DisputeImage WHERE idQImage = ", string(idQImage));
    try
        image = fetch(conn, query);
    catch e
        msgbox(strcat("Error ", char(e.message)), "Warning", "error");
    end

    % Dispositivos de captura obtenidos por HLD
    query = strcat("SELECT percentage, brand, model FROM HLD INNER JOIN Device ON HLD.idDevice = Device.idDevice WHERE idQImage = ",string(idQImage)," ORDER BY percentage DESC");
    try
        devices = fetch(conn, query);
    catch e
        msgbox(strcat("Error ", char(e.message)), "Warning", "error");
    end

    % Total de dispositivos
    query = "SELECT COUNT(idDevice) AS nDevices FROM Device WHERE img_count >= 1;";

    try
        nDevices = fetch(conn, query);
        nDevices = string(nDevices.nDevices);
    catch e
        msgbox(strcat("Error ", char(e.message)), "Warning", "error");
    end
    
    tableHTML = "<tr><th>Dispositivo</th><th>Coincidencia</th></tr>";
    tablePDF = "";

    for i=1 : height(devices)
        tableHTML = strcat(tableHTML, "<tr><td style='border:black solid 1px;'>",string(devices.brand(i))," ",string(devices.model(i)),"</td><td style='border:black solid 1px;'>",string(devices.percentage(i)),"%</td></tr>");
        tablePDF = strcat(tablePDF, "doc.text(20, ",string(i * 10 + 120),", 'Dispositivo: ",string(devices.brand(i))," ",string(devices.model(i))," Coincidencia: ",string(devices.percentage(i)),"%');");
    end
    

    text = strcat("<!DOCTYPE html>" + ...
        "<html lang='es'>" + ...
            "<head>" + ...
                "<meta charset='UTF-8'>" + ...
                "<title>Informe ",nCase,"</title>" + ...
            "</head>" + ...
            "<body id = 'report'>" + ...
                "<header style='text-align: center'>" + ...
                    "<img src='..\..\src\SCI-H.png' alt='logo' height='100px' id='img'><br>" + ...
                    "<b>Source camera identification by Hellinger Distance</b><hr>" + ...
                    "<h1>INFORME DE RESULTADOS</h1>" + ...
                "</header>" + ...
                "<p><b>Fecha:</b> ",string(date),"<br>" + ...
                "<b>No. de Caso:</b> ",nCase,"<br>" + ...
                "<b>Nombre del Analista:</b> ",string(user.name),"<br>" + ...
                "<h3>Descripcion del caso</h3>" + ...
                "Se recibe la imágen de disputa <b>", string(image.file),"</b> y ",string(nDevices)," dispositivos de captura " + ...
                "de los cuales se obtuvieron al menos 15 imágenes de referencia. Al aplicar el " + ...
                "clasificador basado en HLD se encontró que el dispositivo de captura de " + ...
                "la imagen en disputa es <b>",string(devices.brand(1))," ",string(devices.model(1))," con un porcentaje de identificación del ",string(devices.percentage(1)),"%</b>.<br></p>" + ...
                "<h3>Tabla de resultados</h3>" + ...
                "<table style='border:black solid 1px;'>",tableHTML,"</table>" + ...
                "<p style='text-align: center'>____________________________<br>Firma</p>" + ...
                "<button id='convert2pdf'>Convert pdf</button>" + ...
                "<script src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'></script>" + ...
                "<script src='https://html2canvas.hertzen.com/dist/html2canvas.min.js'></script>" + ...
                "<script>" + ...
                    "const { jsPDF } = window.jspdf;" + ...
                    "document.getElementById('convert2pdf').addEventListener('click', (e) => {savePDF();});" + ...
                    "function savePDF() {" + ...
                    "let doc = new jsPDF();" + ...
                    "doc.setFontSize(14);" + ...
                    "doc.text(20, 20, 'Fecha: ",string(date),"');" + ...
                    "doc.text(20, 30, 'No. de Caso: ",nCase,"');" + ...
                    "doc.text(20, 40, 'Nombre del Analista: ",string(user.name),"');" + ...
                    "doc.text(20, 60, 'Descripcion del caso');" + ...
                    "const splitDes = doc.splitTextToSize('Se recibe la imágen de disputa ",string(image.file)," y ",string(nDevices)," dispositivos de captura de los cuales se obtuvieron al menos 15 imágenes de referencia. Al aplicar el clasificador basado en HLD se encontró que el dispositivo de captura de " + ...
                    "la imagen en disputa es ",string(devices.brand(1))," ",string(devices.model(1))," con un porcentaje de identificación del ",string(devices.percentage(1)),"% ', 170);" + ...
                    "doc.text(20, 70, splitDes );" + ...
                    "doc.text(20, 120, 'Resultados');",tablePDF, "doc.text(100, 240, '____________________________', {align:'center'});" + ...
                    "doc.text(95, 250, 'Firma');" + ...
                    "doc.save();}" + ...
                "</script>" + ...
            "</body>" + ...
        "</html>");

    file = strcat("images\Reports\", nCase, ".html");
    writelines(text, file)

    % Actualizar contador
    query = strcat("UPDATE User SET nReports = nReports+1 WHERE idUser = ", string(idUser));

    try
        fetch(conn, query);
    catch e
        msgbox(strcat("Error ", char(e.message)), "Warning", "error");
    end


    open(file);